site_name: OWIN-D
theme: readthedocs
repo_url: https://github.com/OWIN-JS/OWIN-D/
include_search: true
docs_dir: '.'
site_dir: 'dest'
site_favicon: favicon.ico
pages:
- ['index.md', 'Home']
- ['About.md', 'Overview', 'About OWIN-D']
- ['Things.md', 'Overview', 'Things']
- ['Functions.md', 'Overview', 'Functions']
- ['Specification.md', 'Specification', 'OWIN-D v1.0']
theme:  readthedocs
theme_dir: _theme
