site_name: OWIN-D
theme: readthedocs
repo_url: https://github.com/OWIN-JS/OWIN-D/
include_search: true
docs_dir: '.'
site_dir: 'dest'
site_favicon: favicon.ico
pages:
- ['index.md', 'Home']
- ['Specification.md', 'Specification', 'OWIN-D']
- ['About.md', 'Overview', 'About']
theme:  readthedocs
